const RoutineSnap = ({ id, routine, routineNo, timeDays }) => {
  const days = [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
  ];
  const timeSlots = [
    "08:00 AM-09:20 AM",
    "09:30 AM-10:50 AM",
    "11:00 AM-12:20 PM",
    "12:30 PM-01:50 PM",
    "02:00 PM-03:20 PM",
    "03:30 PM-04:50 PM",
    "05:00 PM-06:20 PM",
  ];

  const parseSchedule = (scheduleString) => {
    const schedules = [];
    const entries = scheduleString.split(",").map((entry) => entry.trim());
    entries.forEach((entry) => {
      const [day, time] = entry.split("(");
      if (day && time) {
        const [startTime, endTime, ...room] = time.slice(0, -1).split("-");
        schedules.push({ day, startTime, endTime, room: room.join("-") });
      }
    });
    return schedules;
  };

  const getFormattedText = (courseDetails, initial, roomNo) => {
    return `${courseDetails}<br />[${initial}] ${roomNo}`;
  };

  const getCourseDetails = (day, time, routine) => {
    if (Array.isArray(routine.courses)) {
      for (let section of routine.courses) {
        const schedules = parseSchedule(section.classLabSchedule);
        for (let schedule of schedules) {
          if (
            schedule.day === day &&
            time === `${schedule.startTime}-${schedule.endTime}`
          ) {
            const formattedText = getFormattedText(
              section.courseDetails,
              section.empShortName,
              schedule.room
            );
            return <div dangerouslySetInnerHTML={{ __html: formattedText }} />;
          }
        }
      }
    }
    return "";
  };

  return (
    <div
      id={id}
      className="hidden w-[1280px] h-auto px-14 py-20 bg-gray-50 dark:bg-slate-950"
    >
      <div className="overflow-x-auto mb-6 border-2 border-purple-700 rounded-xl">
      <div className="flex justify-between bg-purple-700 p-4 text-white">
        <h2 className="text-lg font-bold text-center">Routine #{routineNo}</h2>
        <p className="text-center font-semibold">{timeDays}</p>
      </div>
        <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
          <thead className="bg-gray-300 dark:bg-gray-950">
            <tr>
              <th className="px-6 py-3 pb-6 text-center text-xs font-medium text-black dark:text-white uppercase tracking-wider">
                Time
              </th>
              {days.map((day, idx) => (
                <th
                  key={idx}
                  className="px-6 py-3 pb-6  text-center text-xs font-bold text-gray-800 dark:text-gray-300 uppercase tracking-wider"
                >
                  {day}
                </th>
              ))}
            </tr>
          </thead>
          <tbody className="bg-gray-200 dark:bg-gray-900 divide-y divide-gray-100 dark:divide-gray-700">
            {timeSlots.map((time, rowIndex) => (
              <tr
                key={rowIndex}
                className={
                  rowIndex % 2 === 1 ? "bg-gray-300 dark:bg-gray-950" : ""
                }
              >
                <td className="px-6 py-4 pb-6 whitespace-nowrap text-sm text-center text-black dark:text-white font-semibold">
                  {time}
                </td>
                {days.map((day, colIndex) => (
                  <td
                    key={colIndex}
                    className="px-6 py-2 pb-6 whitespace-nowrap text-sm text-center text-black dark:text-white font-semibold"
                  >
                    {getCourseDetails(day, time, routine)}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <p className="text-center text-sm text-gray-500 dark:text-gray-400">
        generated by: <b>https://automate-routine.vercel.app/</b>
      </p>
    </div>
  );
};

export default RoutineSnap;
